apiVersion: v2
name: mortgage-ai
description: A ready-made template for creating new AI Quickstarts
type: application
version: 0.1.0
appVersion: "latest"
keywords:
  - mortgage-ai
home: https://github.com/example/mortgage-ai
sources:
  - https://github.com/example/mortgage-ai
maintainers:
  - name: Development Team
    email: dev@example.com
